### ISSUE TITLE
Add demo screenshot in README.md

### ISSUE THREAD

**Issue by florentroques** [inveniosoftware/invenio-records-ui#90]
Hi,

Thanks for everything you are doing at Invenio for bringing up a digital library platform.

In order to ease the adoption of your software, could you add screenshots to this package so we have a visual, helping us project ourselves into what you are trying to show to world, address with this package.

This would be of tremendous help.

Thank you.
Have a blissful evening.

**Comment by lnielsen** [comment]
Thanks for the suggestion. We're trying to centralise more of the documentation instead of having these individual module documentation. It's simply to big a workload for us to have to main both and the per module docs often misses the big picture. I'm closing this issue as we're not realistic gonna have time to do it (which you've probably already judge from the long reply time ;-)). A PR is of course welcome. Our main documentation is now in https://invenio.readthedocs.io/en/latest/ and https://inveniordm.docs.cern.ch
